// app/layout.tsx or app/layout.tsx (depending on your structure)

import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { AuthWrapper } from "../components/AuthProvider/AuthProvider";
import Sidebar from './components/sidebar/Sidebar';
import Navbar from './components/navbar/Navbar';
import DashboardGuard from "./components/DashboardGuard/DashboardGuard";
import ThemeShell from "./components/theme/ThemeShell";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <Toaster position="top-right" reverseOrder={false} />
      <AuthWrapper>
        <DashboardGuard requiredRoles={["admin"]}>
          <ThemeShell>
            <Sidebar />
            <div className="flex-1 w-full min-h-screen overflow-y-auto">
              <Navbar />
              <div className="ml-40 pt-[50px] min-h-screen transition-colors duration-500 ease-in-out">
                  
                    {children}
                </div>
            </div>
          </ThemeShell>
        </DashboardGuard>
      </AuthWrapper>
    </>

  );
}
